### ISSUE TITLE
Can't build on ubuntu

### ISSUE THREAD

**Issue by gagathos** [mikrohash/isf-jclient#12]
```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building IOTA Spam Fund Java Client 1.0.5
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.iota:jota:jar:0.9.11-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.375 s
[INFO] Finished at: 2018-02-27T12:58:08-05:00
[INFO] Final Memory: 9M/304M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project isf-jclient: Could not resolve dependencies for project com.iotaspam:isf-jclient:jar:1.0.5: Could not find artifact org.iota:jota:jar:0.9.11-SNAPSHOT -> [Help 1]

```

Any ideas?
I thought it would be a git submodule issue but I couldn't find any missing dependencies locally. Is it a config issue?

**Comment by vuapo-eth** [comment]
You have to locally install the iota.lib.java repository via Maven before compiling the spammer. We forgot to mention this in the README.md, will be updated very soon. Here is how to do it:

    $ cd ~/somewhere/
    $ wget https://github.com/iotaledger/iota.lib.java/archive/master.zip
    $ unzip master.zip
    $ cd iota.lib.java-master
    $ mvn install

Alternatively using `git`:

    $ cd ~/somewhere/
    $ git clone https://github.com/iotaledger/iota.lib.java
    $ cd iota.lib.java
    $ mvn install

**Comment by vuapo-eth** [comment]
Instructions were added to the README.md: https://github.com/mikrohash/isf-jclient#2-install-the-dependencies
