### ISSUE TITLE
1.0.8 - request award error

### ISSUE THREAD

**Issue by PJanisio** [mikrohash/isf-jclient#14]
`[17:03:46] [API-Mngr]  [DBG] invalid json: <br /><b>Warning</b>:  Missing argument 4 for authenticate(), called in /var/www/web28365566/html/isf/api/v1.0/balance.php on line 19 and defined in <b>/var/www/web28365566/html/isf/api/v1.0/authenticate.php</b> on line <b>3</b><br />{"success":true,"error":"","balance":20715,"reward":"15","nonce":1519923825}`

`[17:03:46] [API-Mngr]  [WRN] requesting reward balance failed (error is probably caused by our API, write us at contact@iotaspam.com if it persists: 'A JSONObject text must begin with '{' at 1 [character 2 line 1]'), trying again in 5 seconds
`

**Comment by vuapo-eth** [comment]
We were just updating our API. Should already be fixed by now.

**Comment by PJanisio** [comment]
I`m trying to run most updated version of jar :) Maybe I was to fast, lets wait a while and I will close the issue.

By the way - nice error handler :)
