### ISSUE TITLE
jota compilation failure: Perhaps you are running on a JRE rather than a JDK?

### ISSUE THREAD

**Issue by arnelap** [mikrohash/isf-jclient#17]
On Window 10, following the steps in readme.md I got the following errors:

jota: Compilation failure: Perhaps you are running on a JRE rather than a JDK?

isf-jclient: Could not resolve dependencies for project com.iotaspam:isf-jclient:jar:1.0.9: Could not find artifact org.iota:jota:jar:0.9.11-SNAPSHOT ->

Installing JDK 9.04 and subsequantly running the command line:
set JAVA_HOME=C:\Program Files\Java\jdk-9.0.4
fixed the issue for me.  

Hope that helps.

**Comment by vuapo-eth** [comment]
Thank you! We changed it from JRE to JDK in the README.md: https://github.com/mikrohash/isf-jclient#windows

**Comment by arnelap** [comment]
please update the download link as well: http://www.oracle.com/technetwork/java/javase/downloads/index.html

**Comment by arnelap** [comment]
:)

**Comment by vuapo-eth** [comment]
forgot about that, corrected now. Thanks!
