### ISSUE TITLE
Password is shown in plain text. (v1.0.1)

### ISSUE THREAD

**Issue by laubblaeser** [mikrohash/isf-jclient#3]
The title says it all, the password is shown in plain text in version 1.0.1.

**Comment by vuapo-eth** [comment]
we have intentionally changed it to visible because otherwise it's too easy to type in wrong characters (especially for people who are not used to work with consoles and just use `Ctrl+v`)

**Comment by laubblaeser** [comment]
I personally would prefer the password to be hidden but will close the issue regardless. Thanks for the reply.
