### ISSUE TITLE
[Question] - Start daemon args

### ISSUE THREAD

**Issue by jgordor** [mikrohash/isf-jclient#5]
There is a way to start `java -jar isf-jclient-1.0.2.jar` with some arg to say the client to do the `start` command?

I'm tryng to start with nohup in a server (detached from current shell):
```
nohup java -jar isf-jclient-1.0.2.jar &
```

But the client is waiting the `Please enter a command [start/rewards/config/debug]`

**Comment by vuapo-eth** [comment]
thanks for the suggestion, will be implemented in the next version!

**Comment by vuapo-eth** [comment]
feature can now be used in v1.0.3

**Comment by jgordor** [comment]
Thanks 👍
