### ISSUE TITLE
balance is 0

### ISSUE THREAD

**Issue by tunlong** [mikrohash/isf-jclient#8]
I did about 100 comfirmed transactions, my balance is still 0

**Comment by tunlong** [comment]
Maybe there is some delay, now my balance is not 0.

**Comment by vuapo-eth** [comment]
You are right, there is a delay. As soon as a spam address contains  300 transactions, it will be sent to our website, where it will be delayed another 30 minutes (in order for more transactions to confirm) before you receive your reward.
